baseURL = "https://theapplegates.com"
title = "Living My Life"
theme = "zzo"

[algolia]
  index = "Blog-billberry"
  key =  "d8864e42069310e84006c2a07afa45d7"
  appID =  "YJB53K8LH1"


defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

summaryLength = 60
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

enableGitInfo = true
googleAnalytics = "UA-147090349-5"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  
  [scripts] {
    "index-and-send": "hugo-algolia -s"
}

  
  
  
  [outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = "true"

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]	

[outputs]
home = ["HTML", "RSS", "Algolia"]
